# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LIOLOG
subtitle: liolok's logs
description: 岂有文章倾社稷, 从来奸佞覆乾坤.
keywords: [LIOLOG, liolok]
author: liolok
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://liolok.github.io/
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# # Deployment
# ## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repo: https://github.com/liolok/liolok.github.io.git
#   branch: master

# 以下是新增字段

# 引号半角变全角问题
# https://github.com/hexojs/hexo/issues/1981
marked:
  smartypants: false

# hexo-pwa
# Progressive Web Apps (PWA) plugin
pwa:
  manifest:
    path: /manifest.json
    body:
      lang: zh-CN
      name: LIOLOG
      description: liolok's GitHub Pages
      start_url: /
      scope: /
      background-color: '#ffffff'
      theme_color: '#000000'
      display: standalone
      icons:
        - src: /images/icon/pwa_launcher/48.png
          sizes: 48x48
          type: image/png
        - src: /images/icon/pwa_launcher/72.png
          sizes: 72x72
          type: image/png
        - src: /images/icon/pwa_launcher/96.png
          sizes: 96x96
          type: image/png
        - src: /images/icon/pwa_launcher/144.png
          sizes: 144x144
          type: image/png
        - src: /images/icon/pwa_launcher/192.png
          sizes: 192x192
          type: image/png
        - src: /images/icon/pwa_launcher/512.png
          sizes: 512x512
          type: image/png
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
        strategy: cacheFirst
      - pattern: !!js/regexp /\//
        strategy: networkFirst
  priority: 5

# hexo-generator-sitemap
# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
    path: sitemap.xml
