# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LIOLOG
subtitle: liolok's logs
description: 岂有文章倾社稷，从来奸佞覆乾坤。
keywords: [LIOLOG, liolok]
author: 李皓奇
language: [en, zh-Hans]
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://liolok.github.io
root: /
permalink: :title/
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '    '

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: ''

# Fix issue: halfwidth quotation marks rendered to fullwidth
## Reference: https://github.com/hexojs/hexo/issues/1981#issuecomment-229309844
marked:
  smartypants: false

# Plugin: PWA (Progressive Web App)
## Docs: https://github.com/jiangtj-lab/hexo-next-pwa#configure
pwa:
  manifest:
    path: /manifest.json
    body:
      name: liolok's logs
      short_name: LIOLOG
      start_url: /
      theme_color: '#000000'
      background_color: '#ffffff'
      orientation: portrait-primary
      display: standalone
      icons:
        - src: /images/sakamoto/launcher_192.png
          sizes: 192x192
          type: image/png
          puspose: any
        - src: /images/sakamoto/launcher_512.png
          sizes: 512x512
          type: image/png
          puspose: any
        - src: /images/sakamoto/launcher_maskable.png
          sizes: 240x240
          type: image/png
          purpose: maskable
  serviceWorker:
    path: /sw.js
    options:
      importScripts:
        - https://cdn.jsdelivr.net/npm/workbox-sw@4.3.1/build/workbox-sw.min.js
      runtimeCaching:
        - urlPattern: !!js/regexp /\//
          handler: NetworkFirst
          options:
            cacheName: index
        - urlPattern: !!js/regexp /\.(?:js|css)$/
          handler: StaleWhileRevalidate
          options:
            cacheName: js-css
        - urlPattern: !!js/regexp /\.(?:png|gif|jpg|jpeg|svg)$/
          handler: CacheFirst
          options:
            cacheName: images
            expiration:
              maxEntries: 60
              maxAgeSeconds: 2592000 # 30 * 24 * 60 * 60
        - urlPattern: !!js/regexp /^https:\/\/fonts\.googleapis\.com/
          handler: StaleWhileRevalidate
          options:
            cacheName: google-fonts-stylesheets
        - urlPattern: !!js/regexp /^https:\/\/fonts\.gstatic\.com/
          handler: CacheFirst
          options:
            cacheName: google-fonts-webfonts
            cacheableResponse:
              statuses: [0, 200]
            expiration:
              maxAgeSeconds: 31536000 # 365 * 24 * 60 * 60
      # offlineGoogleAnalytics: true

# Plugin: Sitemap Generator
## Docs: https://github.com/hexojs/hexo-generator-sitemap#options
sitemap:
  path: sitemap.xml

# Plugin: utterances, a comments widget for NexT
## Demo: https://utteranc.es/
## Docs: https://github.com/theme-next/hexo-next-utteranc
utteranc:
  enable: true
  repo: liolok/liolok.github.io
  # pathname: pathname # pathname, url, title, og:title
  # theme: github-light # github-light, github-dark, github-dark-orange, icy-dark, dark-blue, photon-dark
  # cdn: https://utteranc.es/client.js
  # priority: # If you want to modify priority, please config in **hexo**
