name: Pages
# (https://hexo.io/docs/github-pages.html)
on:
  push:
    branches:
      - source # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history
          submodules: true # SSH URLs will be auto converted to HTTPS

      - name: Change post files modified time
        run: | # Use markdown files' last commit date as their modified time
          files=$(find source -name '*.md')  # find all markdown files in ./source/
          function get_last_ct { git log -1 --format="@%ct" "$1"; }  # UNIX timestamp
          function set_mtime { touch --no-create --time=modify --date="$1" "$2"; }
          for file in $files; do set_mtime $(get_last_ct $file) $file; done

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master # deploying branch
          force_orphan: true # deploy branch with only the latest commit
